# -*- coding: utf-8 -*-

# Copyright (C) 2018 Martin Bukatovič <martin.bukatovic@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.


from lxml import etree
import pytest


from testutil import xmlparse_testcase


# xml namespaces
NS = {'h': 'http://www.w3.org/1999/xhtml'}


@pytest.mark.parametrize("builder", [
    pytest.mark.sphinx('html', 'html', testroot='requirementlist-nested'),
    pytest.mark.sphinx('xmlexport', 'xmlexport', testroot='requirementlist-nested'),
    ])
def test_requirementlist_minimal(app, status, warning, builder):
    """
    Just checking that this doesn't fail.
    """
    app.builder.build_all()


@pytest.mark.sphinx('html', testroot='requirementlist-nested')
def test_requirementlist_present_nested_html(app, status, warning):
    """
    Check that all requirements are present in the list generated by
    requirementlist directive. Also checking that test cases are listed under
    one (selected) requirement.
    """
    app.builder.build_all()
    # parse requirements overview document
    doc_tree = xmlparse_testcase(app.outdir, "requirements", "html")
    # find and check the requirement list
    req_list = doc_tree.xpath(
        '//h:div[@id="requirements"]/h:ul/h:li',
        namespaces=NS)
    assert len(req_list) == 4
    # check that the list contains all requirements
    req_items = [i.text for i in req_list]
    assert "FOO-ALL" in req_items
    assert "FOO-111" in req_items
    assert "FOO-112" in req_items
    assert "FOO-212" in req_items
    # check that all test cases are listed under FOO-ALL
    foo_all_case_list = doc_tree.xpath(
        '//h:div[@id="requirements"]/h:ul/h:li[text()="FOO-ALL"]//h:li',
        namespaces=NS)
    assert len(foo_all_case_list) == 4
    foo_all_case_items = [''.join(i.itertext()) for i in foo_all_case_list]
    assert "/test_bar" in foo_all_case_items
    assert "/test_foo" in foo_all_case_items
    assert "/baz/test_one" in foo_all_case_items
    assert "/baz/test_two" in foo_all_case_items
