# -*- coding: utf8 -*-

# Copyright (C) 2017 Martin Bukatovič <martin.bukatovic@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.


from pylatest.xdocutils import directives
from pylatest.xdocutils import htmltranslator
from pylatest.xdocutils import nodes
from pylatest.xdocutils import roles
from pylatest.xdocutils import transforms


def setup(app):
    # pylatest roles
    app.add_role("rhbz", roles.redhat_bugzilla_role)
    app.add_role("pylaref", roles.pylaref_html_role)

    # pylatest directives
    app.add_directive("test_step", directives.TestActionDirective)
    app.add_directive("test_result", directives.TestActionDirective)
    app.add_directive("requirement", directives.RequirementDirective)

    # pylatest nodes (generated by directives above)
    for node_name in nodes.node_class_names:
        node_class = getattr(nodes, node_name)
        visit_func = getattr(htmltranslator, "visit_" + node_name)
        depart_func = getattr(htmltranslator, "depart_" + node_name)
        app.add_node(node_class, html=(visit_func, depart_func))

    # pylatest transforms (translates pylatest nodes into human readable form)
    app.add_transform(transforms.TestActionsTableTransform)
    app.add_transform(transforms.RequirementSectionTransform)

    # sphinx plugin metadata
    return {'version': '0.0.5'}
